import next from 'eslint-config-next/core-web-vitals'
import nextTypescript from 'eslint-config-next/typescript'

/**
 * What the linter is here for, and what it is deliberately not here for.
 *
 * `tsc` refuses anything that does not type-check and the tests say whether the
 * app behaves. Neither can see unreferenced code left behind by a refactor, an
 * accessible name drifting from the control it belongs to, or a `useEffect`
 * whose dependency list is out of step with what it reads — which is how a
 * polling table quietly stops polling. That is what this is for.
 *
 * Imported flat rather than through FlatCompat: `next lint` is gone in Next 16
 * and `eslint-config-next` now ships flat config arrays.
 */
const config = [
  {
    ignores: [
      '.next/**',
      'node_modules/**',
      'next-env.d.ts',
      // Generated by shadcn and updated by regenerating rather than editing.
      // Rules nobody is going to act on are rules everybody learns to skip.
      'components/ui/**',
    ],
  },
  ...next,
  ...nextTypescript,
  {
    rules: {
      // `tsc` is the gate on types. Where `any` survives it is at a boundary
      // the linter cannot see past, so flagging it adds noise, not an action.
      '@typescript-eslint/no-explicit-any': 'off',

      // The React Compiler rules, deliberately warnings rather than errors.
      //
      // They fire eleven times on this codebase and every one of them is on a
      // pattern that is doing what it should: reading a preference out of
      // localStorage on mount, because it cannot be read while the page is
      // being rendered on the server; clearing a raise amount when the legal
      // range changes; putting the cards away on a new deal; a countdown
      // asking the clock what time it is. None of them is a bug, and all of
      // them are covered by tests and were watched working in a browser.
      //
      // The idiomatic answers exist — `useSyncExternalStore` for the storage
      // reads, remounting on a `key` for the resets, holding the computed
      // value in the tick for the countdown — and they are six refactors of
      // working UI for no change a player could see. Worth doing next time
      // that code is opened for another reason; not worth doing to turn a
      // check green.
      //
      // Left as warnings so the list stays visible and the check stays honest.
      // An `eslint .` that fails on day one is an `eslint .` nobody runs.
      'react-hooks/set-state-in-effect': 'warn',
      'react-hooks/purity': 'warn',
      'react-hooks/refs': 'warn',
    },
  },
]

export default config
